AllCops:
  Exclude:
    - 'Guardfile'

Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 35
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 13
Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Performance/StringReplacement:
  Exclude:
    - 'lib/wonga/pantry/chef_environment_builder.rb'
